print left ('Baze podataka',4)
print len('Baze podataka')
print lower('BAZE podataka')
print ltrim('    Baze podataka')
print replace('Borg borgira borgijom','borg','zork')
print replicate ('baze',2)
print reverse ('Baze')
print right('Baze podataka',5)
print rtrim('Baze podataka    ')
print substring('Baze podataka',6,7)
print upper('BAZE podataka')